image: atlassian/default-image:4

definitions:
  steps:
    - step: &build-push
        name: Build & Push Docker Images
        services:
          - docker
        script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t $DOCKER_USERNAME/backend:$BITBUCKET_COMMIT  ./backend
          - docker build -t $DOCKER_USERNAME/frontend:$BITBUCKET_COMMIT ./frontend
          - docker tag $DOCKER_USERNAME/backend:$BITBUCKET_COMMIT  $DOCKER_USERNAME/backend:latest
          - docker tag $DOCKER_USERNAME/frontend:$BITBUCKET_COMMIT $DOCKER_USERNAME/frontend:latest
          - docker push $DOCKER_USERNAME/backend:$BITBUCKET_COMMIT
          - docker push $DOCKER_USERNAME/backend:latest
          - docker push $DOCKER_USERNAME/frontend:$BITBUCKET_COMMIT
          - docker push $DOCKER_USERNAME/frontend:latest

    - step: &terraform-apply
        name: Terraform — Provision AWS Infrastructure
        image: hashicorp/terraform:1.7.0
        script:
          - cd terraform
          - terraform init
          - terraform validate
          - terraform plan -input=false -out=tfplan
          - terraform apply -auto-approve tfplan

    - step: &deploy-k8s
        name: Deploy to Kubernetes (EKS)
        image: amazon/aws-cli:2.15.0
        script:
          - curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          - chmod +x kubectl && mv kubectl /usr/local/bin/
          - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
          - sed -i "s|DOCKER_USERNAME/backend:latest|$DOCKER_USERNAME/backend:$BITBUCKET_COMMIT|g"  k8s/backend-deployment.yaml
          - sed -i "s|DOCKER_USERNAME/frontend:latest|$DOCKER_USERNAME/frontend:$BITBUCKET_COMMIT|g" k8s/frontend-deployment.yaml
          - kubectl apply -f k8s/namespace.yaml
          - kubectl apply -f k8s/postgres-configmap.yaml
          - kubectl apply -f k8s/postgres-pvc.yaml
          - kubectl apply -f k8s/postgres-deployment.yaml
          - kubectl apply -f k8s/postgres-service.yaml
          - kubectl apply -f k8s/backend-deployment.yaml
          - kubectl apply -f k8s/backend-service.yaml
          - kubectl apply -f k8s/frontend-deployment.yaml
          - kubectl apply -f k8s/frontend-service.yaml
          - kubectl apply -f k8s/ingress.yaml
          - kubectl rollout status deployment/backend  -n devops-app --timeout=120s
          - kubectl rollout status deployment/frontend -n devops-app --timeout=120s
          - kubectl get pods -n devops-app

pipelines:
  branches:
    main:
      - step: *build-push
      - step: *terraform-apply
      - step: *deploy-k8s
